GET http://10.10.117.159:5188/api/status-keluarga

###
POST http://10.10.117.159:5188/api/status-keluarga
content-type: application/json
{
    "statusKeluarga": "kakak",
    "userCreated": "andry"
}

###
GET http://10.10.117.159:5188/api/status-keluarga